baseURL: https://aidfulai.github.io
languageCode: en-us
title: aidful.ai 🤝
theme: "PaperMod"

params:
  env: production
  defaultTheme: dark
  disableThemeToggle: true
  ShowShareButtons: true
  #Sharebuttons: ["linkedin", "twitter"]  # only show the selected ones
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: Hello, I'm Daniel
    Content: This page is my personal blog which teaches you about the artificial intelligence (AI) revolution and how to use AI as your assistant.
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/aidfulai"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/aidfulai"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Daniel Bender"
  contact: "schrodinger@aidfulai.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 40